### ISSUE TITLE
Versatile Layout Understanding via Conjugate Graph

### ISSUE THREAD

**Issue by imagine5am** [Transkribus/TranskribusDU#12]
I read in the paper Versatile Layout Understanding via Conjugate Graph ([paper url](https://ieeexplore.ieee.org/document/8978117)) and in the paper, they mention that this repository contains their methods and evaluation algorithms. Where can I find code related to this?

**Comment by DRRV** [comment]
Hi, 
you can find the gnn part in https://github.com/Transkribus/TranskribusDU/blob/master/TranskribusDU/gcn/gcn_models.py
It's used in https://github.com/Transkribus/TranskribusDU/blob/master/TranskribusDU/gcn/DU_Model_ECN.py

If you want to replicate  experiments or use it, you can have a look at: https://github.com/Transkribus/TranskribusDU/wiki/Usecase%3A-StAZH

It was designed to be used in the framework of the Transkribus application. We have also a more stand-alone application in pytorch/pyg.

Tell me if you need more help, I will try to update the wiki accordingly.

**Comment by imagine5am** [comment]
What is pytorch/pyg?

**Comment by jlmeunier** [comment]
https://pytorch-geometric.readthedocs.io/en/latest/
